// ignore_for_file: constant_identifier_names

enum PaymentStatus{
 BAD_REQUEST,
 AUTHORIZATION_FAILED,
 PAYMENT_SUCCESS,
 INTERNAL_SERVER_ERROR,
 PAYMENT_ERROR,
 TRANSACTION_NOT_FOUND,
 PAYMENT_PENDING,
 PAYMENT_DECLINED,
 TIMED_OUT,
 UNKNOWN_ERROR,
}